version: '3'

services:
  ganblr:
    image: ganblr-image
    ports:
      - "8000:8000"
    depends_on:
      - db

  ganblr++:
    image: ganblrplusplus-image
    ports:
      - "8001:8001"
    depends_on:
      - db

  meg:
    image: meg-image
    ports:
      - "8002:8002"
    depends_on:
      - db

  tablegan:
    image: tablegan-image
    ports:
      - "8003:8003"
    depends_on:
      - db

  ctgan:
    image: ctgan-image
    ports:
      - "8004:8004"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: